database:
    # the name of the JDBC driver, mysql in our case
    driverClass: "com.mysql.jdbc.Driver"
    # the username
    user: "root"
    # the password
    password: "root"
    # the JDBC URL; the database is called DWGettingStarted
    url: "jdbc:mysql://localhost:3306/sakila"
    properties:
            hibernate.dialect:org.hibernate.dialect.MySQL5Dialect
            hibernate.hbm2ddl.auto: create

